plugins:
  - jekyll-remote-theme

remote_theme: wet-boew/gcweb-jekyll

title: Search UI for Canada.ca Search

defaults:
  - scope:
      path: "" # Ensure it's applied to all pages
    values:
      layout: default

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - docker-compose.yml
  - Gruntfile.js
  - dist/
  - package.json
  - package-lock.json
  - LICENSE
  - CONDE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - SECURITY.md
  - README.md
  - todo.md
